# Use a base image with Java installed
FROM openjdk:11

# Set the working directory in the container
WORKDIR /grocery_store

# Copy the JAR file built from your Spring Boot application to the container
COPY /grocery_store-1.0.0.jar /grocery_store/grocery_store-1.0.0.jar

# Set environment variables for PostgreSQL connection
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=postgres

# Expose the port your Spring Boot application is running on
EXPOSE 8080

# Command to run the Spring Boot application when the container starts
CMD ["java", "-jar", "grocery_store-1.0.0.jar"]
